#Static Portfolio content
portfolio:
 tagline: "I create responsive, interactive user experiences with modern front-end technologies."
 tech: 
  - JavaScript
  - React (+Native)
  - AngularJS
  - Backbone
  - Gulp
  - SASS
  - HTML5

 
 work:
  - RAM
  - dressbarn
  - maurices
  - Fenway Sports Management
  - SNAP - AutoMagic Lock


title: Amber Cook - Front-End Developer
email: hello@ambercook.codes
description: > 
 Front-End Developer Amber Cook's portfolio.
keywords: >
 amber, cook, portfolio, web developer, front-end, javascript
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: >
github_username:  ambercook

# Build settings
markdown: kramdown
include: ['_pages']
